### ISSUE TITLE
switchWidget doesnt work

### ISSUE THREAD

**Issue by remzany** [tawk/tawk-messenger-vue-3#12]
In the documentation there is switchWidget option (https://github.com/tawk/tawk-messenger-vue-3/blob/add-switchWidget-api/docs/api-reference.md). But if I try to access it as stated in the documentation:
```
      this.switchWidget({
            propertyId : 'your-property-id',
            widgetId : 'your-widget-id'
        }, function() {
            // do something
        });
```
      
     it doesn't work. Even if I go directly to browser where tawkto container is visible, and open console and try to call: window.Tawk_API.switchWidget it displays that switchWidget is not a function. It seems that logic for it is missing. Is this in development or is there some config in dashboard to check so it works or something? Thank you in advance

**Comment by jaoaustero** [comment]
@remzany did you call it before the widget loads? This is working in my local test & in our production

**Comment by remzany** [comment]
Hello, sorry for late reply. It also works for me now. Thank you.
