### ISSUE TITLE
Provide CHANGELOG with Version Updates

### ISSUE THREAD

**Issue by chrisspiegl** [tawk/tawk-messenger-vue-3#13]
Please start providing a change log either in form of a file or with the release/tag on GitHub.

Right now, it's a manual job to check what changed and how the new version may impact deployment.

Thank you.

**Comment by jaoaustero** [comment]
Thank you @chrisspiegl I written changelog #14

**Comment by chrisspiegl** [comment]
Thank you. That's going to be great moving forward to track what's happening and how things are changing.
