### ISSUE TITLE
Package not found on npm registry

### ISSUE THREAD

**Issue by trokeibunor** [tawk/tawk-messenger-vue-3#2]
Hello Please this package is not yet available on the  npm registry, please when would it be available

**Comment by jaoaustero** [comment]
Hi @trokeibunor the vue 3 version is still under review by the team, will mentioned you here when it's published.

**Comment by jaoaustero** [comment]
Hi @trokeibunor It was now published, I will closing this issue.

NPM: https://www.npmjs.com/package/@tawk.to/tawk-messenger-vue-3
